# Generated by Django 3.2.2 on 2021-06-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_2342',
            options={'verbose_name': 'Пара группы 2342', 'verbose_name_plural': 'Расписание группы 2342'},
        ),
        migrations.AlterField(
            model_name='group_2342',
            name='classroom',
            field=models.CharField(max_length=10, null=True, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='group_2342',
            name='teacher',
            field=models.CharField(max_length=70, null=True, verbose_name='Преподаватель'),
        ),
    ]
