# Generated by Django 3.2.2 on 2021-06-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210624_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_2121m',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='group_2122m',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='group_2161m',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='group_2171m',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='group_2261m',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Аудитория'),
        ),
    ]
