# Generated by Django 3.2.2 on 2021-06-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210624_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_2321',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='group_2322',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='group_2341',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='group_2342',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='group_2361',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='group_2371',
            name='classroom',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Аудитория'),
        ),
    ]
