# Generated by Django 3.2.2 on 2021-07-03 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210625_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_2121m',
            options={'ordering': ['time', 'day'], 'verbose_name': 'Пара группы 02121-ДМ', 'verbose_name_plural': 'Расписание группы 02121-ДМ'},
        ),
        migrations.AlterModelOptions(
            name='group_2122m',
            options={'ordering': ['time', 'day'], 'verbose_name': 'Пара группы 02122-ДМ', 'verbose_name_plural': 'Расписание группы 02122-ДМ'},
        ),
        migrations.AlterModelOptions(
            name='group_2161m',
            options={'ordering': ['time', 'day'], 'verbose_name': 'Пара группы 02161-ДМ', 'verbose_name_plural': 'Расписание группы 02161-ДМ'},
        ),
        migrations.AlterModelOptions(
            name='group_2171m',
            options={'ordering': ['time', 'day'], 'verbose_name': 'Пара группы 02171-ДМ', 'verbose_name_plural': 'Расписание группы 02171-ДМ'},
        ),
        migrations.AlterModelOptions(
            name='group_2261m',
            options={'ordering': ['time', 'day'], 'verbose_name': 'Пара группы 02261-ДМ', 'verbose_name_plural': 'Расписание группы 02261-ДМ'},
        ),
        migrations.AlterModelOptions(
            name='group_2321',
            options={'ordering': ['time', 'day'], 'verbose_name': 'Пара группы 02321-ДБ', 'verbose_name_plural': 'Расписание группы 02321-ДБ'},
        ),
        migrations.AlterModelOptions(
            name='group_2322',
            options={'ordering': ['time', 'day'], 'verbose_name': 'Пара группы 02322-ДБ', 'verbose_name_plural': 'Расписание группы 02322-ДБ'},
        ),
        migrations.AlterModelOptions(
            name='group_2341',
            options={'ordering': ['time', 'day'], 'verbose_name': 'Пара группы 02341-ДБ'},
        ),
        migrations.AlterModelOptions(
            name='group_2342',
            options={'ordering': ['time', 'day'], 'verbose_name': 'Пара группы 02342-ДБ'},
        ),
        migrations.AlterModelOptions(
            name='group_2361',
            options={'ordering': ['time', 'day'], 'verbose_name': 'Пара группы 02361-ДБ', 'verbose_name_plural': 'Расписание группы 02361-ДБ'},
        ),
        migrations.AlterModelOptions(
            name='group_2371',
            options={'ordering': ['time', 'day'], 'verbose_name': 'Пара группы 02371-ДБ', 'verbose_name_plural': 'Расписание группы 02371-ДБ'},
        ),
        migrations.AlterModelTable(
            name='group_2341',
            table='Расписание группы 02341-ДБ',
        ),
        migrations.AlterModelTable(
            name='group_2342',
            table='Расписание группы 02342-ДБ',
        ),
    ]
