# Generated by Django 3.2.2 on 2021-11-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20211121_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_model',
            old_name='teacher',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='news_model',
            old_name='classroom',
            new_name='text',
        ),
    ]
