# Generated by Django 3.2.2 on 2022-02-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20211121_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group_2121m',
            options={'verbose_name': 'Пара группы 02121-ДМ', 'verbose_name_plural': 'Расписание группы 02121-ДМ'},
        ),
        migrations.AlterModelOptions(
            name='group_2122m',
            options={'verbose_name': 'Пара группы 02122-ДМ', 'verbose_name_plural': 'Расписание группы 02122-ДМ'},
        ),
        migrations.AlterModelOptions(
            name='group_2161m',
            options={'verbose_name': 'Пара группы 02161-ДМ', 'verbose_name_plural': 'Расписание группы 02161-ДМ'},
        ),
        migrations.AlterModelOptions(
            name='group_2171m',
            options={'verbose_name': 'Пара группы 02171-ДМ', 'verbose_name_plural': 'Расписание группы 02171-ДМ'},
        ),
        migrations.AlterModelOptions(
            name='group_2261m',
            options={'verbose_name': 'Пара группы 02261-ДМ', 'verbose_name_plural': 'Расписание группы 02261-ДМ'},
        ),
        migrations.AlterModelOptions(
            name='group_2321',
            options={'verbose_name': 'Пара группы 02321-ДБ', 'verbose_name_plural': 'Расписание группы 02321-ДБ'},
        ),
        migrations.AlterModelOptions(
            name='group_2322',
            options={'verbose_name': 'Пара группы 02322-ДБ', 'verbose_name_plural': 'Расписание группы 02322-ДБ'},
        ),
        migrations.AlterModelOptions(
            name='group_2341',
            options={'verbose_name': 'Пара группы 02341-ДБ', 'verbose_name_plural': 'Расписание группы 02341-ДБ'},
        ),
        migrations.AlterModelOptions(
            name='group_2342',
            options={'verbose_name': 'Пара группы 02342-ДБ', 'verbose_name_plural': 'Расписание группы 02342-ДБ'},
        ),
        migrations.AlterModelOptions(
            name='group_2361',
            options={'verbose_name': 'Пара группы 02361-ДБ', 'verbose_name_plural': 'Расписание группы 02361-ДБ'},
        ),
        migrations.AlterModelOptions(
            name='group_2371',
            options={'verbose_name': 'Пара группы 02371-ДБ', 'verbose_name_plural': 'Расписание группы 02371-ДБ'},
        ),
        migrations.AlterField(
            model_name='news_model',
            name='header',
            field=models.CharField(max_length=40, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='text',
            field=models.CharField(max_length=700, verbose_name='Текст статьи'),
        ),
    ]
