# Generated by Django 3.2.2 on 2022-03-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220206_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_model',
            name='header',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='text',
            field=models.CharField(max_length=7000, verbose_name='Текст статьи'),
        ),
    ]
