# Generated by Django 3.2.2 on 2022-03-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220316_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_model',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='group_2121m',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='group_2122m',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='group_2161m',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='group_2171m',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='group_2261m',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='group_2321',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='group_2322',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='group_2341',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='group_2342',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='group_2361',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='group_2371',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterModelTable(
            name='news_model',
            table='Новости',
        ),
    ]
